#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  Gawain — llama.cpp LoRA Fine-tuning (Linux / Mac)
#
#  Prerequisites:
#    1. llama.cpp built:  make -j8   (or  make GGML_CUDA=1 -j8  for NVIDIA GPU)
#    2. Base model in GGUF format in train/models/
#    3. Training data:    python train/prepare_data.py
#
#  Run from project root:  ./train/finetune.sh
# ─────────────────────────────────────────────────────────────────────────────

set -e

# ── EDIT THESE ────────────────────────────────────────────────────────────────
# Path to your compiled llama.cpp directory
LLAMA_DIR="$HOME/llama.cpp"

# Base model file (must be in GGUF format in train/models/)
BASE_MODEL="train/models/Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"

# Output LoRA adapter
LORA_OUT="train/models/lora-gawain.bin"

# Final merged model
OUTPUT_MODEL="train/models/gawain-finetuned.gguf"

# Training file (generated by prepare_data.py)
TRAIN_FILE="train/data/train.txt"

# GPU layers to offload (0 = CPU only, 35 = most of 8B model fits on 8GB VRAM)
GPU_LAYERS=35

# LoRA rank (16 = good default; 32 = more capacity but slower/more VRAM)
LORA_RANK=16

# Training epochs (10 is good for <500 examples; reduce if you see overfitting)
EPOCHS=10

# Context length
CTX=2048
# ─────────────────────────────────────────────────────────────────────────────

FINETUNE_BIN="$LLAMA_DIR/build/bin/llama-finetune"
EXPORT_BIN="$LLAMA_DIR/build/bin/llama-export-lora"

# Fallback to old binary names
[ ! -f "$FINETUNE_BIN" ] && FINETUNE_BIN="$LLAMA_DIR/finetune"
[ ! -f "$EXPORT_BIN" ]   && EXPORT_BIN="$LLAMA_DIR/export-lora"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║          Gawain — llama.cpp Fine-tuning              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# ── Prerequisite checks ───────────────────────────────────────────────────────
if [ ! -f "$FINETUNE_BIN" ]; then
    echo "ERROR: llama-finetune not found at $FINETUNE_BIN"
    echo ""
    echo "Build llama.cpp first:"
    echo "  git clone https://github.com/ggerganov/llama.cpp"
    echo "  cd llama.cpp"
    echo "  make -j8                    # CPU"
    echo "  make GGML_CUDA=1 -j8       # NVIDIA GPU"
    exit 1
fi

if [ ! -f "$BASE_MODEL" ]; then
    echo "ERROR: Base model not found: $BASE_MODEL"
    echo ""
    echo "Download it with:"
    echo "  pip install huggingface_hub"
    echo "  huggingface-cli download \\"
    echo "    bartowski/Meta-Llama-3.1-8B-Instruct-GGUF \\"
    echo "    Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf \\"
    echo "    --local-dir train/models/"
    exit 1
fi

if [ ! -f "$TRAIN_FILE" ]; then
    echo "Generating training data..."
    python train/prepare_data.py
fi

# ── Step 1: LoRA fine-tuning ──────────────────────────────────────────────────
echo "Step 1/2: Running LoRA fine-tuning..."
echo "  Base model:  $BASE_MODEL"
echo "  Output LoRA: $LORA_OUT"
echo "  Epochs:      $EPOCHS"
echo "  LoRA rank:   $LORA_RANK"
echo "  GPU layers:  $GPU_LAYERS"
echo ""

"$FINETUNE_BIN" \
    --model-base  "$BASE_MODEL" \
    --train-data  "$TRAIN_FILE" \
    --lora-out    "$LORA_OUT" \
    --ctx         "$CTX" \
    --epochs      "$EPOCHS" \
    --batch       4 \
    --lr          0.0003 \
    --lora-r      "$LORA_RANK" \
    --lora-alpha  32 \
    --threads     "$(nproc)" \
    --gpu-layers  "$GPU_LAYERS"

# ── Step 2: Merge LoRA into base model ───────────────────────────────────────
echo ""
echo "Step 2/2: Merging LoRA adapter into base model..."

"$EXPORT_BIN" \
    --model  "$BASE_MODEL" \
    --lora   "$LORA_OUT" \
    --output "$OUTPUT_MODEL"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Fine-tuning complete!                                   ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "Fine-tuned model: $OUTPUT_MODEL"
echo ""
echo "Next steps:"
echo "  1. Import into Ollama:"
echo "       ollama create gawain-finetuned -f train/Modelfile.finetuned"
echo "  2. Test it:"
echo "       ollama run gawain-finetuned 'Show me revenue by year'"
echo "  3. Update .env:"
echo "       OLLAMA_MODEL=gawain-finetuned"
echo ""
