@echo off
REM ─────────────────────────────────────────────────────────────────────────────
REM  Gawain — llama.cpp LoRA Fine-tuning (Windows)
REM
REM  Prerequisites:
REM    1. llama.cpp built with CUDA: cmake -B build -DGGML_CUDA=ON && cmake --build build --config Release -j8
REM    2. Base model in GGUF format in train/models/
REM    3. Training data:  python train/prepare_data.py
REM
REM  Run from project root:  train\finetune.bat
REM ─────────────────────────────────────────────────────────────────────────────

setlocal EnableDelayedExpansion

REM ── EDIT THESE ───────────────────────────────────────────────────────────────
REM Path to your compiled llama.cpp directory
set LLAMA_DIR=C:\llama.cpp

REM Base model file (must be in GGUF format in train/models/)
set BASE_MODEL=train\models\Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf

REM Output LoRA adapter
set LORA_OUT=train\models\lora-gawain.bin

REM Final merged model
set OUTPUT_MODEL=train\models\gawain-finetuned.gguf

REM Training file (generated by prepare_data.py)
set TRAIN_FILE=train\data\train.txt

REM GPU layers to offload (0 = CPU only, 35 = most of 8B model)
set GPU_LAYERS=35

REM LoRA rank (16 = good default; 32 = more capacity but slower)
set LORA_RANK=16

REM Training epochs
set EPOCHS=10

REM Context length
set CTX=2048
REM ─────────────────────────────────────────────────────────────────────────────

echo.
echo ╔══════════════════════════════════════════════════════════╗
echo ║          Gawain — llama.cpp Fine-tuning              ║
echo ╚══════════════════════════════════════════════════════════╝
echo.

REM Check prerequisites
if not exist "%LLAMA_DIR%\build\bin\Release\llama-finetune.exe" (
    if not exist "%LLAMA_DIR%\build\bin\llama-finetune.exe" (
        echo ERROR: llama-finetune.exe not found in %LLAMA_DIR%\build\bin\
        echo Build llama.cpp first:
        echo   cd %LLAMA_DIR%
        echo   cmake -B build -DGGML_CUDA=ON
        echo   cmake --build build --config Release -j8
        exit /b 1
    )
)

if not exist "%BASE_MODEL%" (
    echo ERROR: Base model not found: %BASE_MODEL%
    echo Download it:
    echo   pip install huggingface_hub
    echo   huggingface-cli download bartowski/Meta-Llama-3.1-8B-Instruct-GGUF Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf --local-dir train/models/
    exit /b 1
)

if not exist "%TRAIN_FILE%" (
    echo Generating training data...
    python train\prepare_data.py
    if errorlevel 1 ( echo ERROR: Failed to generate training data & exit /b 1 )
)

REM Find the finetune binary
set FINETUNE_BIN=%LLAMA_DIR%\build\bin\Release\llama-finetune.exe
if not exist "!FINETUNE_BIN!" set FINETUNE_BIN=%LLAMA_DIR%\build\bin\llama-finetune.exe

REM Find the export-lora binary
set EXPORT_BIN=%LLAMA_DIR%\build\bin\Release\llama-export-lora.exe
if not exist "!EXPORT_BIN!" set EXPORT_BIN=%LLAMA_DIR%\build\bin\llama-export-lora.exe

echo Step 1/2: Running LoRA fine-tuning...
echo   Base model:  %BASE_MODEL%
echo   Output LoRA: %LORA_OUT%
echo   Epochs:      %EPOCHS%
echo   LoRA rank:   %LORA_RANK%
echo   GPU layers:  %GPU_LAYERS%
echo.

"!FINETUNE_BIN!" ^
    --model-base  "%BASE_MODEL%" ^
    --train-data  "%TRAIN_FILE%" ^
    --lora-out    "%LORA_OUT%" ^
    --ctx         %CTX% ^
    --epochs      %EPOCHS% ^
    --batch       4 ^
    --lr          0.0003 ^
    --lora-r      %LORA_RANK% ^
    --lora-alpha  32 ^
    --threads     8 ^
    --gpu-layers  %GPU_LAYERS%

if errorlevel 1 (
    echo.
    echo ERROR: Fine-tuning failed. Check the output above.
    exit /b 1
)

echo.
echo Step 2/2: Merging LoRA adapter into base model...

"!EXPORT_BIN!" ^
    --model  "%BASE_MODEL%" ^
    --lora   "%LORA_OUT%" ^
    --output "%OUTPUT_MODEL%"

if errorlevel 1 (
    echo.
    echo ERROR: Model export failed.
    exit /b 1
)

echo.
echo ╔══════════════════════════════════════════════════════════╗
echo ║  Fine-tuning complete!                                   ║
echo ╚══════════════════════════════════════════════════════════╝
echo.
echo Fine-tuned model: %OUTPUT_MODEL%
echo.
echo Next steps:
echo   1. Import into Ollama:
echo        ollama create gawain-finetuned -f train\Modelfile.finetuned
echo   2. Test it:
echo        ollama run gawain-finetuned "Show me revenue by year"
echo   3. Update .env:
echo        OLLAMA_MODEL=gawain-finetuned
echo.

endlocal
